routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Route::get('our_backup_database', 'ContactusController@our_backup_database')->name('our_backup_database');

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::routes();
Route::resource('contactus', 'ContactusController');
Route::get('save_cheque_payments', 'admin\SupplierController@save_cheque_payments')->name('save_cheque_payments');
Route::get('customers/save_cheque_payments', 'admin\CompaniesController@save_cheque_payments');
//Route::post('/login', 'UsersController@login');
Route::get('test/cron', 'admin\SalesController@test_cron');

Route::group(['middleware' => ['auth', 'CheckRole']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

// Products Route
    Route::get('products', 'admin\ProductsController@index')->name('products');
    Route::get('zero-products', 'admin\ProductsController@zero_products')->name('zero-products');

    Route::get('add-products', 'admin\ProductsController@add_products')->name('add-products');
    Route::post('store', 'admin\ProductsController@store')->name('store');
    Route::get('delete-product/{id}', 'admin\ProductsController@delete_product')->name('delete-product');
    Route::get('edit-product/{id}', 'admin\ProductsController@edit_product')->name('edit-product');
    Route::post('update-product', 'admin\ProductsController@update_product')->name('update-product');
    Route::get('product-ledger/{id}', 'admin\ProductsController@update_ledger')->name('product-ledger');

    // Currency Route
    Route::post('add-currency', 'HomeController@add_currency')->name('add-currency');
    //map route
    Route::get('users/map', 'admin\CompaniesController@map')->name('users/map');
    Route::post('users/map', 'admin\CompaniesController@map')->name('users/map');
    Route::post('company/get_addresses', 'admin\CompaniesController@get_addresses')->name('company/get_addresses');
    Route::get('company/get_addresses', 'admin\CompaniesController@get_addresses')->name('company/get_addresses');

    // Supplier Route
    Route::resource('supplier', 'admin\SupplierController');
    Route::resource('assets', 'admin\AssetsController');
    Route::get('supplier-payment/{id}', 'admin\SupplierController@supplier_payment')->name('supplier-payment');
    Route::post('get-payment-type', 'admin\SupplierController@get_payment_type')->name('get-payment-type');
    Route::post('dues-payment', 'admin\SupplierController@dues_payment')->name('dues-payment');

    // Supplier Purchase Route
    Route::resource('supplierPurchase', 'admin\PurchaseController');
    Route::put('supplierPurchase/test/{id}', 'admin\PurchaseController@update')->name('supplierPurchase.update');
    Route::resource('supplierReturnPurchase', 'admin\ReturnPurchaseController');
    Route::post('get-product-details', 'admin\PurchaseController@get_product_details')->name('get-product-details');
    Route::get('purchase-details/{id}', 'admin\PurchaseController@purchase_details')->name('purchase=-details');
    Route::get('return_purchase_details/{id}/{redirect}', 'admin\ReturnPurchaseController@return_purchase_details')->name('return_purchase_details');
    Route::get('return_sale_details/{id}/{redirect}', 'admin\ReturnSalesController@return_sale_details')->name('return_sale_details');
    Route::get('purchase/editPurchase/{id}', 'admin\PurchaseController@editPurchase')->name('editPurchase');

    // customer Sales Route
    Route::resource('sales', 'admin\SalesController');
    Route::resource('return_sale', 'admin\ReturnSalesController');
    Route::get('sale/details/{id}', 'admin\SalesController@saleDetails')->name('sale/details');
    Route::get('walking_customers/sale', 'admin\SalesController@walkingCustomerSale')->name('walking_customers/sale');
    Route::get('walking_customers/returnsale', 'admin\ReturnSalesController@walkingCustomerReturnsale')->name('walking_customers/returnsale');
    Route::get('walking_customers', 'admin\SalesController@walkingCustomers')->name('walking_customers');
    Route::get('walking_customers/return', 'admin\ReturnSalesController@walkingCustomersReturn')->name('walking_customers/return');
    Route::post('walking_customers/save', 'admin\SalesController@saveWalkingCustomer')->name('save/walking_customers');
    Route::post('walking_customers/saveReturnSale', 'admin\ReturnSalesController@walkingCustomerSaveReturnsale')->name('save/walking_customers/saveReturnSale');

    //    Route::post('get-product-details', 'admin\PurchaseController@get_product_details')->name('get-product-details');
    // cash in hand Route
    Route::resource('cash_in_hand', 'admin\CashInHandController');

    Route::get('products', 'admin\ProductsController@index')->name('products');
    Route::get('add-products', 'admin\ProductsController@add_products')->name('add-products');
    Route::post('store', 'admin\ProductsController@store')->name('store');

    Route::get('companies', 'admin\CompaniesController@index')->name('companies');
    Route::get('change-company-status/{id}', 'admin\CompaniesController@changeStatus')->name('change.company.status');
    Route::get('change-bank-status/{id}', 'admin\BankAccController@changeStatus')->name('change.bank.status');
    Route::get('change-salesman-status/{id}', 'admin\AreaPersonController@changeStatus')->name('change.saleman.status');
    Route::get('change-employee-status/{id}', 'admin\EmployeesController@changeStatus')->name('change.employee.status');
    Route::get('inactive-companies', 'admin\CompaniesController@inactiveCompanies')->name('inactive.companies');
    Route::get('customer/ledger/{id}', 'admin\CompaniesController@show')->name('customer/ledger');

    Route::get('company/edit/{id}', 'admin\CompaniesController@edit')->name('company/edit');
    Route::get('company/delete/{id}', 'admin\CompaniesController@destroy')->name('company/delete');
    Route::post('company/update', 'admin\CompaniesController@update')->name('company/update');
    Route::get('Company/add', 'admin\CompaniesController@create')->name('Company/add');
    Route::post('company/store', 'admin\CompaniesController@store')->name('company/store');
    Route::get('company/payment/{id}', 'admin\CompaniesController@customer_payment')->name('company/payment');
    Route::post('company/payment_type', 'admin\CompaniesController@get_payment_type')->name('company/payment_type');
    Route::post('company/save_payment', 'admin\CompaniesController@save_payment')->name('company/save_payment');


    //Banks Routes

    Route::get('bank_acc', 'admin\BankAccController@index')->name('bank_acc');
    Route::get('bank_acc/add', 'admin\BankAccController@create')->name('bank_acc/add');
    Route::post('bank_acc/store', 'admin\BankAccController@store')->name('bank_acc/store');
    Route::get('bank_acc/edit/{id}', 'admin\BankAccController@edit')->name('bank_acc/edit');
    Route::post('bank_acc/update', 'admin\BankAccController@update')->name('bank_acc/update');

    Route::get('bank_acc/destroy/{id}', 'admin\BankAccController@destroy')->name('bank_acc/destroy');
    Route::get('bank_acc/show/{id}', 'admin\BankAccController@show')->name('bank_acc/show');

    //Employees Routes
    Route::resource('employee', 'admin\EmployeesController');
    Route::resource('cities', 'admin\CitiesController');
    Route::resource('manufacturing_companies', 'admin\ManufacturingCompaniesController');
    Route::resource('product_qty', 'admin\ProductQtyController');
    Route::get('employee/employee_ledger/{id}', 'admin\EmployeesController@employee_ledger')->name('employee/employee_ledger');
    Route::post('employee/advance', 'admin\EmployeesController@advance')->name('employee/advance');
    Route::post('employee/save_paid_payment', 'admin\EmployeesController@save_paid_payment')->name('employee/save_paid_payment');
    Route::post('employee/payment_type', 'admin\EmployeesController@get_payment_type')->name('employee/payment_type');
    Route::post('cities/update_city', 'admin\CitiesController@update_city')->name('cities/update_city');
    Route::get('salary_details', 'admin\EmployeesController@salary_details')->name('salary_details');
    Route::get('fetch_company', 'admin\ManufacturingCompaniesController@fetch_company')->name('fetch_company');
    Route::get('fetch_quantity', 'admin\ProductQtyController@fetch_qty')->name('fetch_quantity');
    Route::post('product_qty/update', 'admin\ProductQtyController@update_qty')->name('product_qty/update');
    Route::get('fetch_city', 'admin\CitiesController@fetch_city')->name('fetch_city');
    Route::post('manufacturing_companies/update', 'admin\ManufacturingCompaniesController@update_company')->name('manufacturing_companies/update');

    //cron job
    Route::get('employees/employee_payments', 'admin\EmployeesController@employee_payments')->name('assign.salary');

    // Expense Route
    Route::resource('expenses', 'admin\HeadExpensesController');
    Route::resource('subexpenses', 'admin\ExpensesController');
    Route::post('payment-type', 'admin\ExpensesController@get_payment_type')->name('payment-type');

    Route::get('sale/history', 'admin\SalesController@fetch_history')->name('sale/history');
    Route::get('purchase/history', 'admin\PurchaseController@fetch_history')->name('purchase/history');
    Route::get('sale/print_invoice/{id}', 'admin\SalesController@print_invoice')->name('sale/print_invoice');
    Route::resource('area_person', 'admin\AreaPersonController');

    // Supplier Reports Route
    Route::get('supplier-general-report', 'admin\ReportsController@general_report')->name('supplier-general-report');

app/Http/Controllers/admin/ManufacturingCompaniesController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use Session;

class ManufacturingCompaniesController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $employees = DB::table('manufacturing_companies')->orderBy('id', 'desc')->get();
        return view('admin.manufacturing_companies.index')->with('employees', $employees);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
//        dd($request->city);
        DB::table('manufacturing_companies')->insert([
            'company_name' => $request->company_name,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        Session::flash('success', 'Company Added successfully');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function fetch_company() {
        $id = $_GET['id'];
        $employees = DB::table('manufacturing_companies')
                        ->where('id', '=', $id)
                        ->orderBy('id', 'desc')->first();
        echo $employees->company_name;
    }
     public function update_company(Request $request) {
        $id = $request->company_id;
        DB::table('manufacturing_companies')->where('id', $id)->update([
            'company_name' => $request->company_name,
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        Session::flash('success', 'Company Updated successfully');

        return redirect()->back();
    }

    public function destroy($id) {
        DB::table('manufacturing_companies')->where('id', $id)->delete();
        Session::flash('success', 'Company Deleted Successfully');
        return redirect()->back();
    }


}

resources/views/admin/manufacturing_companies/index.blade.php
@extends('layouts.admin')

@section('style')

<style>
    .currentMonth{
        font-weight: bold;
    }
</style>
@endsection

@section('content')

<div class="be-content">
    <div class="page-head">
        <h2 class="page-head-title">Manufacturing Companies</h2>
        <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb page-head-nav">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                <li class="breadcrumb-item active">All Companies List</li>
            </ol>
        </nav>
    </div>
    <div class="main-content container-fluid">
        <div class="row">
            <div class="col-sm-12">
                @if(Session::has('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                    <div class="icon"><span class="mdi mdi-check"></span></div>
                    <div class="message"><strong> {{ Session::get('success') }} </strong></div>
                </div>
                @endif
                <div class="card card-table">
                    <div class="card-header">Companies List
                        <div class="tools dropdown">
                            <a href="#" data-toggle="modal" data-target="#addCityModal"  class="btn btn-rounded btn-space btn-primary"><i class="fas fa-plus-circle"></i> Add New Company</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover table-fw-widget" id="table1">
                            <thead>
                                <tr>
                                    <th>Companies</th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($employees as $product)
                                <tr>
                                    <td>{{ $product->company_name }}</td>
                                    <td>
                                        <a onclick="editCity({{$product->id}})" href="#" class="btn btn-outline-primary btn-space btn-sm">Edit</a>
                                        <form onsubmit="return confirm('Are you sure')" method="POST" action="{{ route('manufacturing_companies.destroy', ['id'=>$product->id]) }}" style="display:inline;">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button type="submit" class="btn btn-outline-danger btn-space btn-sm">Delete</button>
                                        </form>
                                    </td>
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div id="addCityModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div style='padding: 15px;'>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 style="margin: 0;">Add Company</h4>
                    </div>
                    <form method="POST" id="advancePaymentForm" action="{{route('manufacturing_companies.store')}}">
                        {{csrf_field()}}
                        <div class="modal-body" style="padding:10px">
                            <div class="form-group row" style="padding:0">
                                <label class="col-lg-12">Add Company Name</label>
                                <div class="col-12 col-sm-8 col-lg-12">
                                    <input name="company_name" type="text" class="form-control"  min="0">
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="modal-footer" style="padding:10px">
                        <button type="submit" class="btn btn-outline-success btn-space" form="advancePaymentForm">Save</button>
                        <button type="button" class="btn btn-outline-danger btn-space" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
        <div id="editCityModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div style='padding: 15px;'>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 style="margin: 0;">Edit Manufacturing Company</h4>
                    </div>
                    <form method="POST" id="updateCityForm" action="{{route('manufacturing_companies/update')}}">
                        {{csrf_field()}}

                        <div class="modal-body" style="padding:10px">
                            <div class="form-group row" style="padding:0">
                                <label class="col-lg-12">Edit Company</label>
                                <div class="col-12 col-sm-8 col-lg-12">
                                    <input name="company_id" type="hidden" class="form-control"  min="0">
                                    <input name="company_name" type="text" class="form-control"  min="0">
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="modal-footer" style="padding:10px">
                        <button type="submit" class="btn btn-outline-success btn-space" form="updateCityForm">Save</button>
                        <button type="button" class="btn btn-outline-danger btn-space" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>

@endsection

@section('script')

<script type="text/javascript">

                                            function editCity(cityId){
                                            $('input[name=company_id]').val(cityId);
                                            $.ajax({
                                            url: '{{ route("fetch_company") }}',
                                                    type: 'Get',
                                                    data: {id:cityId},
                                                    success: function(data) {
                                                    $('input[name=company_name]').val(data);
                                                    $('#editCityModal').modal('show');
                                                    }
                                            });
                                            }
                                            
</script>

@endsection