routes/web.php
    Route::get('walking_customers/return', 'admin\ReturnSalesController@walkingCustomersReturn')->name('walking_customers/return');
    Route::post('walking_customers/save', 'admin\SalesController@saveWalkingCustomer')->name('save/walking_customers');
    Route::post('walking_customers/saveReturnSale', 'admin\ReturnSalesController@walkingCustomerSaveReturnsale')->name('save/walking_customers/saveReturnSale');

    //    Route::post('get-product-details', 'admin\PurchaseController@get_product_details')->name('get-product-details');
    // cash in hand Route
    Route::resource('cash_in_hand', 'admin\CashInHandController');

    Route::get('products', 'admin\ProductsController@index')->name('products');
    Route::get('add-products', 'admin\ProductsController@add_products')->name('add-products');
    Route::post('store', 'admin\ProductsController@store')->name('store');

    Route::get('companies', 'admin\CompaniesController@index')->name('companies');
    Route::get('change-company-status/{id}', 'admin\CompaniesController@changeStatus')->name('change.company.status');
    Route::get('change-bank-status/{id}', 'admin\BankAccController@changeStatus')->name('change.bank.status');
    Route::get('change-salesman-status/{id}', 'admin\AreaPersonController@changeStatus')->name('change.saleman.status');
    Route::get('change-employee-status/{id}', 'admin\EmployeesController@changeStatus')->name('change.employee.status');
    Route::get('inactive-companies', 'admin\CompaniesController@inactiveCompanies')->name('inactive.companies');
    Route::get('customer/ledger/{id}', 'admin\CompaniesController@show')->name('customer/ledger');

    Route::get('company/edit/{id}', 'admin\CompaniesController@edit')->name('company/edit');
    Route::get('company/delete/{id}', 'admin\CompaniesController@destroy')->name('company/delete');
    Route::post('company/update', 'admin\CompaniesController@update')->name('company/update');
    Route::get('Company/add', 'admin\CompaniesController@create')->name('Company/add');
    Route::post('company/store', 'admin\CompaniesController@store')->name('company/store');
    Route::get('company/payment/{id}', 'admin\CompaniesController@customer_payment')->name('company/payment');
    Route::post('company/payment_type', 'admin\CompaniesController@get_payment_type')->name('company/payment_type');
    Route::post('company/save_payment', 'admin\CompaniesController@save_payment')->name('company/save_payment');


    //Banks Routes

    Route::get('bank_acc', 'admin\BankAccController@index')->name('bank_acc');
    Route::get('bank_acc/add', 'admin\BankAccController@create')->name('bank_acc/add');
    Route::post('bank_acc/store', 'admin\BankAccController@store')->name('bank_acc/store');
    Route::get('bank_acc/edit/{id}', 'admin\BankAccController@edit')->name('bank_acc/edit');
    Route::post('bank_acc/update', 'admin\BankAccController@update')->name('bank_acc/update');

    Route::get('bank_acc/destroy/{id}', 'admin\BankAccController@destroy')->name('bank_acc/destroy');
    Route::get('bank_acc/show/{id}', 'admin\BankAccController@show')->name('bank_acc/show');

    //Employees Routes
    Route::resource('employee', 'admin\EmployeesController');
    Route::resource('cities', 'admin\CitiesController');
    Route::resource('manufacturing_companies', 'admin\ManufacturingCompaniesController');
    Route::resource('product_qty', 'admin\ProductQtyController');
    Route::get('employee/employee_ledger/{id}', 'admin\EmployeesController@employee_ledger')->name('employee/employee_ledger');
    Route::post('employee/advance', 'admin\EmployeesController@advance')->name('employee/advance');
    Route::post('employee/save_paid_payment', 'admin\EmployeesController@save_paid_payment')->name('employee/save_paid_payment');
    Route::post('employee/payment_type', 'admin\EmployeesController@get_payment_type')->name('employee/payment_type');
    Route::post('cities/update_city', 'admin\CitiesController@update_city')->name('cities/update_city');
    Route::get('salary_details', 'admin\EmployeesController@salary_details')->name('salary_details');
    Route::get('fetch_company', 'admin\ManufacturingCompaniesController@fetch_company')->name('fetch_company');
    Route::get('fetch_quantity', 'admin\ProductQtyController@fetch_qty')->name('fetch_quantity');
    Route::post('product_qty/update', 'admin\ProductQtyController@update_qty')->name('product_qty/update');
    Route::get('fetch_city', 'admin\CitiesController@fetch_city')->name('fetch_city');
    Route::post('manufacturing_companies/update', 'admin\ManufacturingCompaniesController@update_company')->name('manufacturing_companies/update');

    //cron job
    Route::get('employees/employee_payments', 'admin\EmployeesController@employee_payments')->name('assign.salary');

    // Expense Route
    Route::resource('expenses', 'admin\HeadExpensesController');
    Route::resource('subexpenses', 'admin\ExpensesController');
    Route::post('payment-type', 'admin\ExpensesController@get_payment_type')->name('payment-type');

    Route::get('sale/history', 'admin\SalesController@fetch_history')->name('sale/history');
    Route::get('purchase/history', 'admin\PurchaseController@fetch_history')->name('purchase/history');
    Route::get('sale/print_invoice/{id}', 'admin\SalesController@print_invoice')->name('sale/print_invoice');
    Route::resource('area_person', 'admin\AreaPersonController');

    // Supplier Reports Route
    Route::get('supplier-general-report', 'admin\ReportsController@general_report')->name('supplier-general-report');
    Route::post('generate-supplier-general-report', 'admin\ReportsController@generate_supplier_general_report')->name('generate-supplier-general-report');
    Route::get('supplier-report', 'admin\ReportsController@index')->name('supplier-report');
    Route::post('supplier-ledger-report', 'admin\ReportsController@supplier_ledger_report')->name('supplier-ledger-report');

    // Supplier City Reports
    Route::get('supplier-city-report', 'admin\ReportsController@supplier_city_report')->name('supplier-city-report');
    Route::post('get-supplier-city-report', 'admin\ReportsController@get_supplier_city_report')->name('get-supplier-city-report');

    //Customers Reports Route
    Route::get('customer-report', 'admin\ReportsController@customer_report')->name('customer-report');
    Route::post('customer-ledger-report', 'admin\ReportsController@customer_ledger_report')->name('customer-ledger-report');

    //Customers City Reports Route
    Route::get('customer-city-report', 'admin\ReportsController@customer_city_report')->name('customer-city-report');
    Route::post('get-customer-city-report', 'admin\ReportsController@get_customer_city_report')->name('get-customer-city-report');
    // Product Reports Route
    Route::get('product-report', 'admin\ReportsController@product_report')->name('product-report');
    Route::post('product-ledger-report', 'admin\ReportsController@product_ledger_report')->name('product-ledger-report');

    // Product Reports Route
//    Route::get('product-report', 'admin\ReportsController@product_report')->name('product-report');
//    Route::post('product-ledger-report', 'admin\ReportsController@product_ledger_report')->name('product-ledger-report');
    // Purchase Reports Route
//    Route::get('purchase-report', 'admin\ReportsController@purchase_report')->name('purchase-report');
//    Route::post('purchase-ledger-report', 'admin\ReportsController@purchase_ledger_report')->name('purchase-ledger-report');
    // Purchase Reports Route
    Route::get('purchase-report', 'admin\ReportsController@purchase_report')->name('purchase-report');
    Route::post('purchase-ledger-report', 'admin\ReportsController@purchase_ledger_report')->name('purchase-ledger-report');
    // Sale Reports Route
//    Route::get('sale-report', 'admin\ReportsController@sale_report')->name('sale-report');
//    Route::post('sale-ledger-report', 'admin\ReportsController@sale_ledger_report')->name('sale-ledger-report');
    // Return  Purchase Reports Route
    Route::get('return-purchase-report', 'admin\ReportsController@return_purchase_report')->name('return-purchase-report');
    Route::post('return-purchase-ledger-report', 'admin\ReportsController@return_purchase_ledger_report')->name('return-purchase-ledger-report');
    // Expenses Reports Route
//    Route::get('expenses-report', 'admin\ReportsController@expenses_report')->name('expenses-report');
//    Route::post('expense-ledger-report', 'admin\ReportsController@expense_ledger_report')->name('expense-ledger-report');
    // Sale Reports Route
    Route::get('sale-report', 'admin\ReportsController@sale_report')->name('sale-report');
    Route::post('sale-ledger-report', 'admin\ReportsController@sale_ledger_report')->name('sale-ledger-report');
    // Expenses Reports Route
//    Route::get('bank-report', 'admin\ReportsController@bank_report')->name('bank-report');
//    Route::post('bank-ledger-report', 'admin\ReportsController@bank_ledger_report')->name('bank-ledger-report');
    // Return Sale Reports Route
    Route::get('return-sale-report', 'admin\ReportsController@return_sale_report')->name('return-sale-report');
    Route::post('return-sale-ledger-report', 'admin\ReportsController@return_sale_ledger_report')->name('return-sale-ledger-report');
    // Expenses Reports Route
//    Route::get('employee-report', 'admin\ReportsController@employee_report')->name('employee-report');
//    Route::post('employee-ledger-report', 'admin\ReportsController@employee_ledger_report')->name('employee-ledger-report');
    // Expenses Reports Route
    Route::get('expenses-report', 'admin\ReportsController@expenses_report')->name('expenses-report');
    Route::post('expense-ledger-report', 'admin\ReportsController@expense_ledger_report')->name('expense-ledger-report');

    // Bank Reports Route
    Route::get('bank-report', 'admin\ReportsController@bank_report')->name('bank-report');

app/Http/Controllers/admin/ProductQtyController.php
<?php

namespace App\Http\Controllers\admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use DB;
use Session;

class ProductQtyController extends Controller {

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index() {
        $employees = DB::table('product_qty')->orderBy('id', 'desc')->get();
        return view('admin.product_qty.index')->with('employees', $employees);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create() {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request) {
//        dd($request->quantity);
        DB::table('product_qty')->insert([
            'quantity' => $request->quantity,
            'created_at' => date('Y-m-d H:i:s'),
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        Session::flash('success', 'Quantity added successfully');

        return redirect()->back();
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id) {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id) {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id) {
        //
    }

    public function fetch_qty() {
        $id = $_GET['id'];
        $employees = DB::table('product_qty')
                        ->where('id', '=', $id)
                        ->orderBy('id', 'desc')->first();
        echo $employees->quantity;
    }

    public function update_qty(Request $request) {
//        dd($request->all());
        $id = $request->quantity_id;
        DB::table('product_qty')->where('id', $id)->update([
            'quantity' => $request->quantity,
            'updated_at' => date('Y-m-d H:i:s'),
        ]);
        Session::flash('success', 'Quantity Updated successfully');

        return redirect()->back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
     public function destroy($id) {
        DB::table('product_qty')->where('id', $id)->delete();
        Session::flash('success', 'Quantity Deleted Successfully');
        return redirect()->back();
    }

}

resources/views/admin/product_qty/index.blade.php
@extends('layouts.admin')

@section('style')
<style>
    @media 
    only screen and (max-width: 760px),
    (min-device-width: 768px) and (max-device-width: 1024px)  {
        td:nth-of-type(1):before { content: "Type"; }
        td:nth-of-type(2):before { content: "Action"; }
        
    }
</style>
@endsection

@section('content')

<div class="be-content">
    <div class="page-head">
        <h2 class="page-head-title">Product Types</h2>
        <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb page-head-nav">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                <li class="breadcrumb-item active">All Product Types</li>
            </ol>
        </nav>
    </div>
    <div class="main-content container-fluid">
        <div class="row">
            <div class="col-sm-12">
                @if(Session::has('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                    <div class="icon"><span class="mdi mdi-check"></span></div>
                    <div class="message"><strong> {{ Session::get('success') }} </strong></div>
                </div>
                @endif
                <div class="card card-table">
                    <div class="card-header">Product Types
                        <div class="tools dropdown">
                            <a href="#" data-toggle="modal" data-target="#addCityModal"  class="btn btn-rounded btn-space btn-primary"><i class="fas fa-plus-circle"></i> Add Product Type</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover table-fw-widget" id="table1">
                            <thead>
                                <tr>
                                    <th>Product Type</th>
                                    <?php if (auth()->user()->user_type == 1) { ?>

                                        <th>Actions</th>
                                    <?php } ?>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($employees as $product)
                                <tr>
                                    <td><?= ($product->quantity); ?></td>
                                    <?php if (auth()->user()->user_type == 1) { ?>

                                        <td>
                                            <a onclick="editCity({{$product->id}})" href="#" class="btn btn-outline-primary btn-space btn-sm">Edit</a>
                                            <form onsubmit="return confirm('Are you sure')" method="POST" action="{{ route('product_qty.destroy', ['id'=>$product->id]) }}" style="display:inline;">
                                                {{ csrf_field() }}
                                                {{ method_field('DELETE') }}
                                                <button type="submit" class="btn btn-outline-danger btn-space btn-sm">Delete</button>
                                            </form>
                                        </td>
                                    <?php } ?>
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div id="addCityModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div style='padding: 15px;'>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 style="margin: 0;">Add Product Type</h4>
                    </div>
                    <form method="POST" id="advancePaymentForm" action="{{route('product_qty.store')}}">
                        {{csrf_field()}}
                        <div class="modal-body" style="padding:10px">
                            <div class="form-group row" style="padding:0">
                                <label class="col-lg-12">Add Product Type</label>
                                <div class="col-12 col-sm-8 col-lg-12">
                                    <input name="quantity" type="text" class="form-control"  min="0" required>

                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="modal-footer" style="padding:10px">
                        <button type="submit" class="btn btn-outline-success btn-space" form="advancePaymentForm">Save</button>
                        <button type="button" class="btn btn-outline-danger btn-space" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
        <div id="editCityModal" class="modal fade" role="dialog">
            <div class="modal-dialog">

                <!-- Modal content-->
                <div class="modal-content">
                    <div style='padding: 15px;'>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 style="margin: 0;">Edit Product Type</h4>
                    </div>
                    <form method="POST" id="updateCityForm" action="{{route('product_qty/update')}}">
                        {{csrf_field()}}

                        <div class="modal-body" style="padding:10px">
                            <div class="form-group row" style="padding:0">
                                <label class="col-lg-12">Product Type</label>
                                <div class="col-12 col-sm-8 col-lg-12">
                                    <input name="quantity_id" type="hidden" class="form-control"  min="0">
                                    <input name="quantity" type="text" class="form-control"  min="0" required>
                                </div>
                            </div>
                        </div>
                    </form>
                    <div class="modal-footer" style="padding:10px">
                        <button type="submit" class="btn btn-outline-success btn-space" form="updateCityForm">Save</button>
                        <button type="button" class="btn btn-outline-danger btn-space" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>

@endsection

@section('script')
<script type="text/javascript">

    function editCity(cityId){
    $('input[name=quantity_id]').val(cityId);
    $.ajax({
    url: '{{ route("fetch_quantity") }}',
            type: 'Get',
            data: {id:cityId},
            success: function(data) {
            $('input[name=quantity]').val(data);
            $('#editCityModal').modal('show');
            }
    });
    }

</script>

@endsection