routes/web.php
<?php

/*
  |--------------------------------------------------------------------------
  | Web Routes
  |--------------------------------------------------------------------------
  |
  | Here is where you can register web routes for your application. These
  | routes are loaded by the RouteServiceProvider within a group which
  | contains the "web" middleware group. Now create something great!
  |
 */
Route::get('our_backup_database', 'ContactusController@our_backup_database')->name('our_backup_database');

Route::get('/', 'Auth\LoginController@showLoginForm');
Auth::routes();
Route::resource('contactus', 'ContactusController');
Route::get('save_cheque_payments', 'admin\SupplierController@save_cheque_payments')->name('save_cheque_payments');
Route::get('customers/save_cheque_payments', 'admin\CompaniesController@save_cheque_payments');
//Route::post('/login', 'UsersController@login');
Route::get('test/cron', 'admin\SalesController@test_cron');

Route::group(['middleware' => ['auth', 'CheckRole']], function () {
    Route::get('/home', 'HomeController@index')->name('home');

// Products Route
    Route::get('products', 'admin\ProductsController@index')->name('products');
    Route::get('zero-products', 'admin\ProductsController@zero_products')->name('zero-products');

    Route::get('add-products', 'admin\ProductsController@add_products')->name('add-products');
    Route::post('store', 'admin\ProductsController@store')->name('store');
    Route::get('delete-product/{id}', 'admin\ProductsController@delete_product')->name('delete-product');
    Route::get('edit-product/{id}', 'admin\ProductsController@edit_product')->name('edit-product');
    Route::post('update-product', 'admin\ProductsController@update_product')->name('update-product');
    Route::get('product-ledger/{id}', 'admin\ProductsController@update_ledger')->name('product-ledger');

    // Currency Route
    Route::post('add-currency', 'HomeController@add_currency')->name('add-currency');
    //map route
    Route::get('users/map', 'admin\CompaniesController@map')->name('users/map');
    Route::post('users/map', 'admin\CompaniesController@map')->name('users/map');
    Route::post('company/get_addresses', 'admin\CompaniesController@get_addresses')->name('company/get_addresses');
    Route::get('company/get_addresses', 'admin\CompaniesController@get_addresses')->name('company/get_addresses');

    // Supplier Route
    Route::resource('supplier', 'admin\SupplierController');
    Route::resource('assets', 'admin\AssetsController');
    Route::get('supplier-payment/{id}', 'admin\SupplierController@supplier_payment')->name('supplier-payment');
    Route::post('get-payment-type', 'admin\SupplierController@get_payment_type')->name('get-payment-type');
    Route::post('dues-payment', 'admin\SupplierController@dues_payment')->name('dues-payment');

    // Supplier Purchase Route
    Route::resource('supplierPurchase', 'admin\PurchaseController');
    Route::put('supplierPurchase/test/{id}', 'admin\PurchaseController@update')->name('supplierPurchase.update');
    Route::resource('supplierReturnPurchase', 'admin\ReturnPurchaseController');
    Route::post('get-product-details', 'admin\PurchaseController@get_product_details')->name('get-product-details');
    Route::get('purchase-details/{id}', 'admin\PurchaseController@purchase_details')->name('purchase=-details');
    Route::get('return_purchase_details/{id}/{redirect}', 'admin\ReturnPurchaseController@return_purchase_details')->name('return_purchase_details');
    Route::get('return_sale_details/{id}/{redirect}', 'admin\ReturnSalesController@return_sale_details')->name('return_sale_details');
    Route::get('purchase/editPurchase/{id}', 'admin\PurchaseController@editPurchase')->name('editPurchase');

    // customer Sales Route
    Route::resource('sales', 'admin\SalesController');
    Route::resource('return_sale', 'admin\ReturnSalesController');
    Route::get('sale/details/{id}', 'admin\SalesController@saleDetails')->name('sale/details');
    Route::get('walking_customers/sale', 'admin\SalesController@walkingCustomerSale')->name('walking_customers/sale');
    Route::get('walking_customers/returnsale', 'admin\ReturnSalesController@walkingCustomerReturnsale')->name('walking_customers/returnsale');
    Route::get('walking_customers', 'admin\SalesController@walkingCustomers')->name('walking_customers');
    Route::get('walking_customers/return', 'admin\ReturnSalesController@walkingCustomersReturn')->name('walking_customers/return');
    Route::post('walking_customers/save', 'admin\SalesController@saveWalkingCustomer')->name('save/walking_customers');
    Route::post('walking_customers/saveReturnSale', 'admin\ReturnSalesController@walkingCustomerSaveReturnsale')->name('save/walking_customers/saveReturnSale');

    //    Route::post('get-product-details', 'admin\PurchaseController@get_product_details')->name('get-product-details');
    // cash in hand Route
    Route::resource('cash_in_hand', 'admin\CashInHandController');

    Route::get('products', 'admin\ProductsController@index')->name('products');
    Route::get('add-products', 'admin\ProductsController@add_products')->name('add-products');
    Route::post('store', 'admin\ProductsController@store')->name('store');

    Route::get('companies', 'admin\CompaniesController@index')->name('companies');
    Route::get('change-company-status/{id}', 'admin\CompaniesController@changeStatus')->name('change.company.status');
    Route::get('change-bank-status/{id}', 'admin\BankAccController@changeStatus')->name('change.bank.status');
    Route::get('change-salesman-status/{id}', 'admin\AreaPersonController@changeStatus')->name('change.saleman.status');
    Route::get('change-employee-status/{id}', 'admin\EmployeesController@changeStatus')->name('change.employee.status');
    Route::get('inactive-companies', 'admin\CompaniesController@inactiveCompanies')->name('inactive.companies');
    Route::get('customer/ledger/{id}', 'admin\CompaniesController@show')->name('customer/ledger');

    Route::get('company/edit/{id}', 'admin\CompaniesController@edit')->name('company/edit');
    Route::get('company/delete/{id}', 'admin\CompaniesController@destroy')->name('company/delete');
    Route::post('company/update', 'admin\CompaniesController@update')->name('company/update');
    Route::get('Company/add', 'admin\CompaniesController@create')->name('Company/add');
    Route::post('company/store', 'admin\CompaniesController@store')->name('company/store');
    Route::get('company/payment/{id}', 'admin\CompaniesController@customer_payment')->name('company/payment');
    Route::post('company/payment_type', 'admin\CompaniesController@get_payment_type')->name('company/payment_type');
    Route::post('company/save_payment', 'admin\CompaniesController@save_payment')->name('company/save_payment');


    //Banks Routes

    Route::get('bank_acc', 'admin\BankAccController@index')->name('bank_acc');
    Route::get('bank_acc/add', 'admin\BankAccController@create')->name('bank_acc/add');
    Route::post('bank_acc/store', 'admin\BankAccController@store')->name('bank_acc/store');
    Route::get('bank_acc/edit/{id}', 'admin\BankAccController@edit')->name('bank_acc/edit');
    Route::post('bank_acc/update', 'admin\BankAccController@update')->name('bank_acc/update');

    Route::get('bank_acc/destroy/{id}', 'admin\BankAccController@destroy')->name('bank_acc/destroy');
    Route::get('bank_acc/show/{id}', 'admin\BankAccController@show')->name('bank_acc/show');

    //Employees Routes
    Route::resource('employee', 'admin\EmployeesController');
    Route::resource('cities', 'admin\CitiesController');
    Route::resource('manufacturing_companies', 'admin\ManufacturingCompaniesController');
    Route::resource('product_qty', 'admin\ProductQtyController');
    Route::get('employee/employee_ledger/{id}', 'admin\EmployeesController@employee_ledger')->name('employee/employee_ledger');
    Route::post('employee/advance', 'admin\EmployeesController@advance')->name('employee/advance');
    Route::post('employee/save_paid_payment', 'admin\EmployeesController@save_paid_payment')->name('employee/save_paid_payment');
    Route::post('employee/payment_type', 'admin\EmployeesController@get_payment_type')->name('employee/payment_type');
    Route::post('cities/update_city', 'admin\CitiesController@update_city')->name('cities/update_city');
    Route::get('salary_details', 'admin\EmployeesController@salary_details')->name('salary_details');
    Route::get('fetch_company', 'admin\ManufacturingCompaniesController@fetch_company')->name('fetch_company');
    Route::get('fetch_quantity', 'admin\ProductQtyController@fetch_qty')->name('fetch_quantity');
    Route::post('product_qty/update', 'admin\ProductQtyController@update_qty')->name('product_qty/update');
    Route::get('fetch_city', 'admin\CitiesController@fetch_city')->name('fetch_city');
    Route::post('manufacturing_companies/update', 'admin\ManufacturingCompaniesController@update_company')->name('manufacturing_companies/update');

    //cron job
    Route::get('employees/employee_payments', 'admin\EmployeesController@employee_payments')->name('assign.salary');

    // Expense Route
    Route::resource('expenses', 'admin\HeadExpensesController');
    Route::resource('subexpenses', 'admin\ExpensesController');
    Route::post('payment-type', 'admin\ExpensesController@get_payment_type')->name('payment-type');

    Route::get('sale/history', 'admin\SalesController@fetch_history')->name('sale/history');
    Route::get('purchase/history', 'admin\PurchaseController@fetch_history')->name('purchase/history');
    Route::get('sale/print_invoice/{id}', 'admin\SalesController@print_invoice')->name('sale/print_invoice');
    Route::resource('area_person', 'admin\AreaPersonController');

    // Supplier Reports Route
    Route::get('supplier-general-report', 'admin\ReportsController@general_report')->name('supplier-general-report');

resources/views/admin/companies/customer_cheques.blade.php
@extends('layouts.admin')

@section('style')

@endsection

@section('content')

<div class="be-content">
    <div class="page-head">
        <h2 class="page-head-title">Customer</h2>
        <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb page-head-nav">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{route('supplier.index')}}">Customers</a></li>

                <li class="breadcrumb-item active">Customer Cheques</li>
            </ol>
        </nav>
    </div>
    <div class="main-content container-fluid">
        <div class="row">
            <div class="col-sm-12">

                @if(Session::has('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                    <div class="icon"><span class="mdi mdi-check"></span></div>
                    <div class="message"><strong> {{ Session::get('success') }} </strong></div>
                </div>
                @endif

                <div class="card card-table">
                    <div class="card-header">Customer Cheques
                        <div class="tools dropdown">
                            <a href="javascript:" data-toggle="modal" data-target="#purchaseDetailModal" class="btn btn-rounded btn-space btn-primary"><i class="fas fa-plus-circle"></i> Clear Cheques</a>
                        </div>
                    </div>
                    <div class="card-body p-1">
                        <table class="table no-more-tables table-striped table-bordered table-fw-widget" id="table1">
                            <thead>
                                <tr>
                                    <th>Customer Name</th>
                                    <th>Cheque No</th>
                                    <th>Amount</th>
                                    <th>Released On</th>
                                    <th>Payment Type</th>
                                    <th>Is Cleared</th>

                                    <th>Created On</th>
                                    <?php if (auth()->user()->user_type == 1) { ?>
                                        <th>Action</th>
                                    <?php } ?>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($cheques as $ledger)
                                <tr>
                                    <td data-title="Customer Name" >{{ $ledger->name }}</td>
                                    <td data-title="Cheque No">{{ $ledger->cheque_no }}</td>
                                    <td data-title="Amount">{{ $ledger->amount }}</td>
                                    <?php
                                    ?>
                                    <td data-title="Released On">@if($ledger->release_date)
                                            {{ date('Y-m-d', strtotime($ledger->release_date)) }}
                                        @endif
                                    </td>
                                    <td data-title="Payment Type">{{ $ledger->transfer_to }}</td>

                                    <td data-title="Is Cleared"> <?php
                                        if ($ledger->is_clear == 0) {
                                            echo "<span class='text-warning'>Pending</span>";
                                        }
                                        if ($ledger->is_clear == 1) {
                                            echo "<span class='text-success'>Cleared</span>";
                                        }
                                        if ($ledger->is_clear == 2) {
                                            echo "<span class='text-danger'>Not Cleared</span>";
                                        }
                                        ?>
                                    </td>
                                    <td data-title="Created On"> {{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $ledger->created_at)->format('d-m-Y') }}</td>
                                    <?php if (auth()->user()->user_type == 1) { ?>
                                        <td data-title="Action"> 
                                            <?php
                                            if ($ledger->is_clear == 0 || $ledger->is_clear == 2) {
                                                ?>

                                                <a onclick="return confirm('are you sure')" href="{{ route('customer/cheque/delete', ['id' => $ledger->id]) }}" class="btn btn-outline-danger btn-space btn-sm">
                                                    Delete
                                                </a>
                                                <?php
                                            }
                                            ?>
                                        </td>
                                    <?php } ?>
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
        <div id="purchaseDetailModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-xl">

                <!-- Modal content-->
                <div class="modal-content" style="max-width: 100% !important;">
                    <div style='padding: 15px;'>
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 style="margin: 0;">List Of cheques that needs to be cleared</h4>
                    </div>

                    <div class="modal-body" id="purchaseDetailBody" style="padding:10px">
                        <table class="table table-striped table-hover table-fw-widget" id="table1">
                            <thead>
                                <tr>
                                    <th>Customer Name</th>
                                    <th>Cheque No</th>
                                    <th>Amount</th>
                                    <th>Released On</th>
                                    <th>Payment Type</th>
                                    <th>Is Cleared</th>

                                    <th>Created On</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($unclearcheques as $ledger)
                                <tr>
                                    <td>{{ $ledger->name }}</td>
                                    <td>{{ $ledger->cheque_no }}</td>
                                    <td>{{ $ledger->amount }}</td>
                                    <td>{{ date('Y-m-d',strtotime($ledger->release_date)) }}</td>
                                    <td>{{ $ledger->transfer_to }}</td>

                                    <td id="clear<?= $ledger->id ?>"> 
                                        <a href="javascript:" onclick="isclear('clear', '<?= $ledger->id; ?>')"  class="btn btn-success btn-sm">Cleared</a>
                                        <a href="javascript:" onclick="isclear('notclear', '<?= $ledger->id; ?>')" class="btn btn-danger btn-sm">Not Cleared</a>
                                    </td>
                                    <td> {{ date('Y-m-d',strtotime($ledger->created_at)) }}</td>
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <div class="modal-footer" style="padding:10px">
                        <button type="button" class="btn btn-outline-danger btn-space" data-dismiss="modal">Close</button>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

@endsection

@section('script')
<script type="text/javascript">
                                            function isclear(status, id) {

                                                if (confirm('Are You Sure')) {
                                                    $.ajax({
                                                        url: '<?= url('cheque_cleared') ?>',
                                                        type: 'get',
                                                        data: {
                                                            status: status,
                                                            id: id
                                                        },
                                                        success: function (data) {
                                                            data = JSON.parse(data);
                                                            if (data.flag == 1) {
                                                                $('#clear' + id).parents('tr').remove();
                                                                location.reload();
                                                            }
                                                        }
                                                    });
                                                }
                                            }
                                           
</script>

@endsection

resources/views/admin/companies/inactive-companies.blade.php
@extends('layouts.admin')

@section('style')


@endsection

@section('content')

<div class="be-content">
    <div class="page-head">
        <h2 class="page-head-title">Customers</h2>
        <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb page-head-nav">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                <li class="breadcrumb-item active">All Customers List</li>
            </ol>
        </nav>
    </div>
    <div class="main-content container-fluid">
        <div class="row">
            <div class="col-sm-12">
                @if(Session::has('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                    <div class="icon"><span class="mdi mdi-check"></span></div>
                    <div class="message"><strong> {{ Session::get('success') }} </strong></div>
                </div>
                @endif
                @if(Session::has('error'))
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                    <div class="icon"><span class="mdi mdi-check"></span></div>
                    <div class="message"><strong> {{ Session::get('error') }} </strong></div>
                </div>
                @endif
                <div class="card card-table">
                    <div class="card-header">Customers List
                        <div class="tools dropdown">
                            <a href="{{ url('Company/add') }}" class="btn btn-rounded btn-space btn-primary"><i class="fas fa-plus-circle"></i> Add New Customer</a>
                        </div>
                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover table-fw-widget" id="table1">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Contact</th>
                                    <th>Type</th>
                                    <th>Dues</th>
                                    <th>Last Payment</th>
                                    <th>Payment</th>
                                    <th style="white-space:nowrap">Status</th>
                                    <th>Sale</th>
                                    <th>Sale History</th>
                                    <th>Return Sale</th>
                                    <th>Return History</th>
                                    <th>Ledger</th>
                                    <?php if (auth()->user()->user_type == 1) { ?>
                                        <th>Actions</th>
                                    <?php } ?>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($customers as $product)
                                <tr>
                                    <td>{{ $product->name }}</td>
                                    <td>{{ $product->contact }}</td>
<!--                                    <td>{{ $product->email }}</td>
                                    <td>{{ $product->address }}</td>
                                    <td>{{ $product->city }}</td>-->
                                    <td>{{ ucwords($product->type) }}</td>
                                    <td>{{ $product->dues }}</td>

                                    <td>
                                        <span class="text-danger">
                                            <?php
                                            if ($product->last_payment) {
                                                $earlier = new DateTime();
                                                $later = new DateTime($product->last_payment);

                                                $diff = $later->diff($earlier)->format("%a");
                                                if ($diff == 0) {
                                                    echo 'Paid Today';
                                                } elseif ($diff == 1) {
                                                    echo '<b>' . abs($diff) . '</b> day ago';
                                                } else {
                                                    echo '<b>' . abs($diff) . '</b> days ago';
                                                }
                                            } else {
                                                echo 'Not Paid yet';
                                            }
                                            ?>
                                        </span>
                                    </td>
                                    <td>
                                        <a href="{{ route('company/payment', ['id' => $product->id]) }}" class="btn btn-outline-secondary btn-space btn-sm">
                                            Pay
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{route('change.company.status',['id'=>$product->id])}}" class="btn btn-outline-dark btn-space btn-sm">
                                            Move to Active
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ route('sales.show', ['id' => $product->id]) }}" class="btn btn-outline-success btn-space btn-sm">
                                            Sale
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ route('sales.edit', ['id' => $product->id]) }}" class="btn btn-outline-success btn-space btn-sm">
                                            View
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ route('return_sale.show', ['id' => $product->id]) }}" class="btn btn-outline-success btn-space btn-sm">
                                            Return
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ route('return_sale.edit', ['id' => $product->id]) }}" class="btn btn-outline-success btn-space btn-sm">
                                            <!--<a href="#" class="btn btn-outline-success btn-space btn-sm">-->
                                            View
                                        </a>
                                    </td>
                                    <td>
                                        <a href="{{ route('customer/ledger', ['id' => $product->id]) }}" class="btn btn-outline-success btn-space btn-sm">
                                            View
                                        </a>
                                    </td>
                                    <?php if (auth()->user()->user_type == 1) { ?>

                                        <td>
                                            <a href="{{ route('company/edit', ['id' => $product->id]) }}" class="btn btn-outline-primary btn-space btn-sm">Edit</a>
                                        </td>
                                    <?php } ?>
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="requestPayment">
            <div class="modal-dialog modal-md">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3>Request For Payment</h3>
                        <a class="close" data-dismiss="modal">&times;</a>
                    </div>
                    <div class="modal-body">
                        <form method="post" id="messageForm" action="{{route('company/request_payment')}}">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label>Enter Message</label>
                                <input type="hidden" name="customer_id">
                                <textarea class="form-control" name="message"></textarea> 
                            </div>
                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-outline-success">Send</button>
                                <button class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                            </div>
                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')
<script type="text/javascript">
                                                function requestPayment(num){
                                                $('input[name=customer_id]').val(num);
                                                $('#requestPayment').modal('show');
                                                }
                                               
</script>

@endsection