routes/web.php
    Route::get('company/get_addresses', 'admin\CompaniesController@get_addresses')->name('company/get_addresses');

    // Supplier Route
    Route::resource('supplier', 'admin\SupplierController');
    Route::resource('assets', 'admin\AssetsController');
    Route::get('supplier-payment/{id}', 'admin\SupplierController@supplier_payment')->name('supplier-payment');
    Route::post('get-payment-type', 'admin\SupplierController@get_payment_type')->name('get-payment-type');
    Route::post('dues-payment', 'admin\SupplierController@dues_payment')->name('dues-payment');

    // Supplier Purchase Route
    Route::resource('supplierPurchase', 'admin\PurchaseController');
    Route::put('supplierPurchase/test/{id}', 'admin\PurchaseController@update')->name('supplierPurchase.update');
    Route::resource('supplierReturnPurchase', 'admin\ReturnPurchaseController');
    Route::post('get-product-details', 'admin\PurchaseController@get_product_details')->name('get-product-details');
    Route::get('purchase-details/{id}', 'admin\PurchaseController@purchase_details')->name('purchase=-details');
    Route::get('return_purchase_details/{id}/{redirect}', 'admin\ReturnPurchaseController@return_purchase_details')->name('return_purchase_details');
    Route::get('return_sale_details/{id}/{redirect}', 'admin\ReturnSalesController@return_sale_details')->name('return_sale_details');
    Route::get('purchase/editPurchase/{id}', 'admin\PurchaseController@editPurchase')->name('editPurchase');

    // customer Sales Route
    Route::resource('sales', 'admin\SalesController');
    Route::resource('return_sale', 'admin\ReturnSalesController');
    Route::get('sale/details/{id}', 'admin\SalesController@saleDetails')->name('sale/details');
    Route::get('walking_customers/sale', 'admin\SalesController@walkingCustomerSale')->name('walking_customers/sale');
    Route::get('walking_customers/returnsale', 'admin\ReturnSalesController@walkingCustomerReturnsale')->name('walking_customers/returnsale');
    Route::get('walking_customers', 'admin\SalesController@walkingCustomers')->name('walking_customers');
    Route::get('walking_customers/return', 'admin\ReturnSalesController@walkingCustomersReturn')->name('walking_customers/return');
    Route::post('walking_customers/save', 'admin\SalesController@saveWalkingCustomer')->name('save/walking_customers');
    Route::post('walking_customers/saveReturnSale', 'admin\ReturnSalesController@walkingCustomerSaveReturnsale')->name('save/walking_customers/saveReturnSale');

    //    Route::post('get-product-details', 'admin\PurchaseController@get_product_details')->name('get-product-details');
    // cash in hand Route
    Route::resource('cash_in_hand', 'admin\CashInHandController');

    Route::get('products', 'admin\ProductsController@index')->name('products');
    Route::get('add-products', 'admin\ProductsController@add_products')->name('add-products');
    Route::post('store', 'admin\ProductsController@store')->name('store');

    Route::get('companies', 'admin\CompaniesController@index')->name('companies');
    Route::get('change-company-status/{id}', 'admin\CompaniesController@changeStatus')->name('change.company.status');
    Route::get('change-bank-status/{id}', 'admin\BankAccController@changeStatus')->name('change.bank.status');
    Route::get('change-salesman-status/{id}', 'admin\AreaPersonController@changeStatus')->name('change.saleman.status');
    Route::get('change-employee-status/{id}', 'admin\EmployeesController@changeStatus')->name('change.employee.status');
    Route::get('inactive-companies', 'admin\CompaniesController@inactiveCompanies')->name('inactive.companies');
    Route::get('customer/ledger/{id}', 'admin\CompaniesController@show')->name('customer/ledger');

    Route::get('company/edit/{id}', 'admin\CompaniesController@edit')->name('company/edit');
    Route::get('company/delete/{id}', 'admin\CompaniesController@destroy')->name('company/delete');
    Route::post('company/update', 'admin\CompaniesController@update')->name('company/update');
    Route::get('Company/add', 'admin\CompaniesController@create')->name('Company/add');
    Route::post('company/store', 'admin\CompaniesController@store')->name('company/store');
    Route::get('company/payment/{id}', 'admin\CompaniesController@customer_payment')->name('company/payment');
    Route::post('company/payment_type', 'admin\CompaniesController@get_payment_type')->name('company/payment_type');
    Route::post('company/save_payment', 'admin\CompaniesController@save_payment')->name('company/save_payment');


    //Banks Routes

    Route::get('bank_acc', 'admin\BankAccController@index')->name('bank_acc');
    Route::get('bank_acc/add', 'admin\BankAccController@create')->name('bank_acc/add');
    Route::post('bank_acc/store', 'admin\BankAccController@store')->name('bank_acc/store');
    Route::get('bank_acc/edit/{id}', 'admin\BankAccController@edit')->name('bank_acc/edit');
    Route::post('bank_acc/update', 'admin\BankAccController@update')->name('bank_acc/update');

    Route::get('bank_acc/destroy/{id}', 'admin\BankAccController@destroy')->name('bank_acc/destroy');
    Route::get('bank_acc/show/{id}', 'admin\BankAccController@show')->name('bank_acc/show');

    //Employees Routes
    Route::resource('employee', 'admin\EmployeesController');
    Route::resource('cities', 'admin\CitiesController');
    Route::resource('manufacturing_companies', 'admin\ManufacturingCompaniesController');
    Route::resource('product_qty', 'admin\ProductQtyController');
    Route::get('employee/employee_ledger/{id}', 'admin\EmployeesController@employee_ledger')->name('employee/employee_ledger');
    Route::post('employee/advance', 'admin\EmployeesController@advance')->name('employee/advance');
    Route::post('employee/save_paid_payment', 'admin\EmployeesController@save_paid_payment')->name('employee/save_paid_payment');
    Route::post('employee/payment_type', 'admin\EmployeesController@get_payment_type')->name('employee/payment_type');
    Route::post('cities/update_city', 'admin\CitiesController@update_city')->name('cities/update_city');
    Route::get('salary_details', 'admin\EmployeesController@salary_details')->name('salary_details');
    Route::get('fetch_company', 'admin\ManufacturingCompaniesController@fetch_company')->name('fetch_company');
    Route::get('fetch_quantity', 'admin\ProductQtyController@fetch_qty')->name('fetch_quantity');
    Route::post('product_qty/update', 'admin\ProductQtyController@update_qty')->name('product_qty/update');
    Route::get('fetch_city', 'admin\CitiesController@fetch_city')->name('fetch_city');
    Route::post('manufacturing_companies/update', 'admin\ManufacturingCompaniesController@update_company')->name('manufacturing_companies/update');

    //cron job
    Route::get('employees/employee_payments', 'admin\EmployeesController@employee_payments')->name('assign.salary');

    // Expense Route
    Route::resource('expenses', 'admin\HeadExpensesController');
    Route::resource('subexpenses', 'admin\ExpensesController');
    Route::post('payment-type', 'admin\ExpensesController@get_payment_type')->name('payment-type');

    Route::get('sale/history', 'admin\SalesController@fetch_history')->name('sale/history');
    Route::get('purchase/history', 'admin\PurchaseController@fetch_history')->name('purchase/history');
    Route::get('sale/print_invoice/{id}', 'admin\SalesController@print_invoice')->name('sale/print_invoice');
    Route::resource('area_person', 'admin\AreaPersonController');

    // Supplier Reports Route
    Route::get('supplier-general-report', 'admin\ReportsController@general_report')->name('supplier-general-report');
    Route::post('generate-supplier-general-report', 'admin\ReportsController@generate_supplier_general_report')->name('generate-supplier-general-report');
    Route::get('supplier-report', 'admin\ReportsController@index')->name('supplier-report');
    Route::post('supplier-ledger-report', 'admin\ReportsController@supplier_ledger_report')->name('supplier-ledger-report');

    // Supplier City Reports
    Route::get('supplier-city-report', 'admin\ReportsController@supplier_city_report')->name('supplier-city-report');
    Route::post('get-supplier-city-report', 'admin\ReportsController@get_supplier_city_report')->name('get-supplier-city-report');

    //Customers Reports Route
    Route::get('customer-report', 'admin\ReportsController@customer_report')->name('customer-report');
    Route::post('customer-ledger-report', 'admin\ReportsController@customer_ledger_report')->name('customer-ledger-report');

    //Customers City Reports Route
    Route::get('customer-city-report', 'admin\ReportsController@customer_city_report')->name('customer-city-report');
    Route::post('get-customer-city-report', 'admin\ReportsController@get_customer_city_report')->name('get-customer-city-report');
    // Product Reports Route
    Route::get('product-report', 'admin\ReportsController@product_report')->name('product-report');
    Route::post('product-ledger-report', 'admin\ReportsController@product_ledger_report')->name('product-ledger-report');

    // Product Reports Route
//    Route::get('product-report', 'admin\ReportsController@product_report')->name('product-report');
//    Route::post('product-ledger-report', 'admin\ReportsController@product_ledger_report')->name('product-ledger-report');
    // Purchase Reports Route
//    Route::get('purchase-report', 'admin\ReportsController@purchase_report')->name('purchase-report');
//    Route::post('purchase-ledger-report', 'admin\ReportsController@purchase_ledger_report')->name('purchase-ledger-report');
    // Purchase Reports Route
    Route::get('purchase-report', 'admin\ReportsController@purchase_report')->name('purchase-report');
    Route::post('purchase-ledger-report', 'admin\ReportsController@purchase_ledger_report')->name('purchase-ledger-report');
    // Sale Reports Route

app/AreaPerson.php
<?php

namespace App;

use App\AreaPersonLedger;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Foundation\Auth\User as Authenticatable;

class AreaPerson extends Authenticatable {

    protected $table = 'area_person';
    protected $guard = 'saleman';



    public function areaperson_ledger(){
        return $this->hasMany('App\AreaPersonLedger');
    }

}

resources/views/admin/area_person/admin_stock_details.blade.php
@extends('layouts.admin')

@section('style')

<style>
    .currentMonth{
        font-weight: bold;
    }
      @media 
    only screen and (max-width: 760px),
    (min-device-width: 768px) and (max-device-width: 1024px)  {
        td:nth-of-type(1):before { content: "Product"; }
        td:nth-of-type(2):before { content: "Qty"; }
        td:nth-of-type(3):before { content: "Invoice No"; }
        td:nth-of-type(4):before { content: "Description"; }
        td:nth-of-type(5):before { content: "Date"; }

    }
</style>
@endsection

@section('content')

<div class="be-content">
    <div class="page-head">
        <h2 class="page-head-title">Stock Details</h2>
        <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb page-head-nav">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{url('area_person')}}">Sales man</a></li>
                <li class="breadcrumb-item"><a href="{{url('sale_man/sales/history',Request::segment(5))}}">Stock</a></li>
                <li class="breadcrumb-item active">Stock Details</li>
            </ol>
        </nav>
    </div>
    <div class="main-content container-fluid">
        <div class="row">
            <div class="col-sm-12">
                @if(Session::has('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                    <div class="icon"><span class="mdi mdi-check"></span></div>
                    <div class="message"><strong> {{ Session::get('success') }} </strong></div>
                </div>
                @endif
                <div class="card card-table">
                    <div class="card-header">Product Stock Details

                    </div>
                    <div class="card-body">
                        <table class="table table-striped table-hover table-fw-widget" id="table1">
                            <thead>
                                <tr>
                                    <th>Product Name</th>
                                    <th>Quantity</th>
                                    <th>Invoice No</th>
                                    <th>Description</th>
                                    <th>Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($employees as $product)
                                <tr>
                                    <td>{{ $product->product_name }}</td>
                                    <td>{{ $product->qty }}</td>
                                    <td>{{ $product->vr_no }}</td>
                                    <td>{{ $product->description }}</td>
                                    <td>{{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $product->created_at)->format('d-m-Y') }}</td>
                               </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

@endsection

@section('script')

<script type="text/javascript">

function editCity(cityId) {
    $('input[name=city_id]').val(cityId);
    $.ajax({
        url: '{{ route("fetch_city") }}',
        type: 'Get',
        data: {id: cityId},
        success: function (data) {
            $('input[name=city]').val(data);
            $('#editCityModal').modal('show');
        }
    });
}

</script>

@endsection

resources/views/admin/area_person/customers.blade.php
@extends('layouts.admin')

@section('style')


@endsection

@section('content')

<div class="be-content">
    <div class="page-head">
        <h2 class="page-head-title">Customers</h2>
        <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb page-head-nav">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>
                <li class="breadcrumb-item active">All Customers List</li>
            </ol>
        </nav>
    </div>
    <div class="main-content container-fluid">
        <div class="row">
            <div class="col-sm-12">
                @if(Session::has('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                    <div class="icon"><span class="mdi mdi-check"></span></div>
                    <div class="message"><strong> {{ Session::get('success') }} </strong></div>
                </div>
                @endif
                @if(Session::has('error'))
                <div class="alert alert-danger alert-dismissible" role="alert">
                    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                    <div class="icon"><span class="mdi mdi-check"></span></div>
                    <div class="message"><strong> {{ Session::get('error') }} </strong></div>
                </div>
                @endif
                <div class="card card-table">
                    <div class="card-header">Customers List

                    </div>
                    <div class="card-body p-1">
                        <table class="table table-striped table-bordered no-more-tables table-fw-widget" id="table1">
                            <thead>
                                <tr>
                                    <th>Name</th>
                                    <th>Contact</th>
                                    <th>Type</th>
                                    <th>Payment</th>
                                    <th>Sale History</th>
                                    <!--<th>Return Sale</th>-->
                                    <!--<th>Return History</th>-->
                                    <th>Ledger</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($customers as $product)
                                <tr>
                                    <td data-title="Name">{{ $product->name }}</td>
                                    <td data-title="Contact">{{ $product->contact }}</td>
                                    <td data-title="Type">{{ ucwords($product->type) }}</td>

                                    <td data-title="Sale History">
                                        <a href="{{ route('customer-payment', ['id' => $product->id]) }}" class="btn btn-outline-secondary btn-space btn-sm">
                                            Pay
                                        </a>
                                    </td>
                                    <td data-title="Ledger">
                                        <a href="{{ route('sale-details', ['id' => $product->id]) }}" class="btn btn-outline-success btn-space btn-sm">
                                            View
                                        </a>
                                    </td>
<!--                                    <td>
                                        <a href="{{ route('return_sale.show', ['id' => $product->id]) }}" class="btn btn-outline-success btn-space btn-sm">
                                            Return
                                        </a>
                                    </td>-->
<!--                                    <td>
                                        <a href="{{ route('return_sale.edit', ['id' => $product->id]) }}" class="btn btn-outline-success btn-space btn-sm">
                                            <a href="#" class="btn btn-outline-success btn-space btn-sm">
                                            View
                                        </a>
                                    </td>-->
                                    <td>
                                        <a href="{{ route('saleman.customer_ledger', ['id' => $product->id]) }}" class="btn btn-outline-success btn-space btn-sm">
                                            View
                                        </a>
                                    </td>
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

        <div class="modal fade" id="requestPayment">
            <div class="modal-dialog modal-md">
                <div class="modal-content">
                    <div class="modal-header">
                        <h3>Request For Payment</h3>
                        <a class="close" data-dismiss="modal">&times;</a>
                    </div>
                    <div class="modal-body">
                        <form method="post" id="messageForm" action="{{route('company/request_payment')}}">
                            {{csrf_field()}}
                            <div class="form-group">
                                <label>Enter Message</label>
                                <input type="hidden" name="customer_id">
                                <textarea class="form-control" name="message"></textarea> 
                            </div>
                            <div class="form-group text-right">
                                <button type="submit" class="btn btn-outline-success">Send</button>
                                <button class="btn btn-outline-danger" data-dismiss="modal">Close</button>
                            </div>
                        </form>

                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')

<script type="text/javascript">
function requestPayment(num) {
    $('input[name=customer_id]').val(num);
    $('#requestPayment').modal('show');
}

</script>

@endsection

resources/views/admin/area_person/edit.blade.php
@extends('layouts.admin')

@section('style')

@endsection

@section('content')

<div class="be-content">
    <div class="page-head">
        <h2 class="page-head-title">Sales man</h2>
        <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb page-head-nav">
                <li class="breadcrumb-item"><a href="{{route('home')}}">Dashboard</a></li>

                <li class="breadcrumb-item"><a href="{{route('area_person.index')}}">Sales man</a></li>
                <li class="breadcrumb-item active">Edit Sales man</li>
            </ol>
        </nav>
    </div>
    <div class="main-content container-fluid">
        <div class="row">
            <div class="col-md-12">
                @if(Session::has('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                    <div class="icon"><span class="mdi mdi-check"></span></div>
                    <div class="message"><strong> {{ Session::get('success') }} </strong></div>
                </div>
                @endif

                <div class="card card-border-color card-border-color-primary">
                    <div class="card-header card-header-divider">Edit Sales man</div>
                    <div class="card-body">
                        <form method="post" action="{{ route('area_person.update', ['id' => $employee->id ]) }}">
                            {{ csrf_field() }}
                            {{ method_field('PATCH') }}

                            <div class="form-group row">
                                <label class="col-12 col-sm-3 col-form-label text-sm-right">Name</label>
                                <div class="col-12 col-sm-8 col-lg-6">
                                    <input class="form-control" name="name" type="text" value="{{$employee->name}}" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-12 col-sm-3 col-form-label text-sm-right">Cnic</label>
                                <div  class="col-12 col-sm-8 col-lg-6">
                                    <input data-mask="cnic" class="form-control" name="cnic" type="text" placeholder="Cnic without dashes" value="{{$employee->cnic}}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-12 col-sm-3 col-form-label text-sm-right">Contact Number</label>
                                <div class="col-12 col-sm-8 col-lg-6">
                                    <input class="form-control" type="text" name="contact" value="{{$employee->contact}}" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-12 col-sm-3 col-form-label text-sm-right">Email Address</label>
                                <div class="col-12 col-sm-8 col-lg-6">
                                    <input class="form-control" type="email" name="email" value="{{$employee->email}}">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-12 col-sm-3 col-form-label text-sm-right">Password</label>
                                <div class="col-12 col-sm-8 col-lg-6">
                                    <input class="form-control" type="password" name="pass" value="">
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-12 col-sm-3 col-form-label text-sm-right">Address</label>
                                <div class="col-12 col-sm-8 col-lg-6">
                                    <input class="form-control" type="test" name="address" value="{{$employee->address}}" required>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-12 col-sm-3 col-form-label text-sm-right">City</label>
                                <div class="col-12 col-sm-8 col-lg-6">
                                    <select name="city" class="form-control" required>
                                        @foreach($cities as $city)
                                        <option value="{{$city->city}}" <?= ($employee->city == $city->city) ? "selected" : ''; ?>>{{ucwords($city->city)}}</option>
                                        @endforeach
                                    </select>
                                </div>
                            </div>
                            <div class="form-group row">
                                <label class="col-12 col-sm-3 col-form-label text-sm-right"></label>
                                <div class="col-12 col-sm-8 col-lg-6 text-center">
                                    <button class="btn btn-primary">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('script')
<script src="{{ asset('public/assets/lib/jquery.maskedinput/jquery.maskedinput.js') }}" type="text/javascript"></script>
<script src="{{ asset('public/assets/js/app-form-masks.js') }}" type="text/javascript"></script>
<script type="text/javascript">
$(document).ready(function () {
    //-initialize the javascript
    App.init();
    App.masks();
});
</script>
@endsection

resources/views/admin/area_person/stock_details.blade.php
@extends('layouts.admin')

@section('style')


<style>
    .currentMonth{
        font-weight: bold;
    }
</style>
@endsection

@section('content')

<div class="be-content">
    <div class="page-head">
        <h2 class="page-head-title">Stock Details</h2>
        <nav aria-label="breadcrumb" role="navigation">
            <ol class="breadcrumb page-head-nav">
                <li class="breadcrumb-item"><a href="{{route('my_dashboard')}}">Dashboard</a></li>
                <li class="breadcrumb-item"><a href="{{route('stock')}}">Stock</a></li>
                <!--<li class="breadcrumb-item active">Stock</li>-->
                <li class="breadcrumb-item active">Stock Details</li>
            </ol>
        </nav>
    </div>
    <div class="main-content container-fluid">
        <div class="row">
            <div class="col-sm-12">
                @if(Session::has('success'))
                <div class="alert alert-success alert-dismissible" role="alert">
                    <button class="close" type="button" data-dismiss="alert" aria-label="Close"><span class="mdi mdi-close" aria-hidden="true"></span></button>
                    <div class="icon"><span class="mdi mdi-check"></span></div>
                    <div class="message"><strong> {{ Session::get('success') }} </strong></div>
                </div>
                @endif
                <div class="card card-table">
                    <div class="card-header">Product Stock Details

                    </div>
                    <div class="card-body p-1">
                        <table class="table table-striped table-bordered no-more-tables table-fw-widget" id="table1">
                            <thead>
                                <tr>
                                    <th>Product Name</th>
                                    <th>Quantity</th>
                                    <th>Date</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($employees as $product)
                                <tr>
                                    <td data-title="Product Name">{{ $product->product_name }}</td>
                                    <td data-title="Quantity">{{ $product->qty }}</td>
                                    <td data-title="Date">{{ Carbon\Carbon::createFromFormat('Y-m-d H:i:s', $product->created_at)->format('d-m-Y') }}</td>
<!--                                    <td>
                                        <a href="{{ route('stock-details', ['id'=>$product->id]) }}" class="btn btn-outline-success btn-space btn-sm">Stock Details</a>
                                    </td>
                                    <td>
                                        <a href="{{ route('area_person.edit', ['id'=>$product->id]) }}" class="btn btn-outline-primary btn-space btn-sm">Edit</a>
                                        <form onsubmit="return confirm('Are you sure')" method="POST" action="{{ route('area_person.destroy', ['id'=>$product->id]) }}" style="display:inline;">
                                            {{ csrf_field() }}
                                            {{ method_field('DELETE') }}
                                            <button type="submit" class="btn btn-outline-danger btn-space btn-sm">Delete</button>
                                        </form>
                                    </td>-->
                                </tr>

                                @endforeach
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>

</div>

@endsection

@section('script')

<script type="text/javascript">

function editCity(cityId) {
    $('input[name=city_id]').val(cityId);
    $.ajax({
        url: '{{ route("fetch_city") }}',
        type: 'Get',
        data: {id: cityId},
        success: function (data) {
            $('input[name=city]').val(data);
            $('#editCityModal').modal('show');
        }
    });
}

</script>

@endsection